# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/naturalfunction"
[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/vitorribeiro1"
[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "substack"
name = "Substack"
url = "https://vitorr.substack.com/"
[social.params]
icon = "brand-substack"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:blog@vitorribeiro.com"
[social.params]
icon = "mail"
